config/routes.rb
Crowdedapp::Application.routes.draw do
  resources :events

  devise_for :users

  get "welcome/index"

  root 'welcome#index'

  

end

app/models/event.rb
class Event < ActiveRecord::Base

  validates_numericality_of :severity
  validates_presence_of :severity
  validates_presence_of :location
  validates_presence_of :title

  def self.severity
    (1..5).to_a
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
   before_filter :authenticate_user!, except: [:index, :show]


  def index
    @events = Event.all
    @search = Event.search(params[:q])
    @events = @search.result
  end

  def new 
    @event = Event.new
  end


  def edit  
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event), notice: 'Event was successfully updated.' 
    else
      render action: 'edit'
    end
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to event_path(@event)
    else 
      render action: 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private
  def event_params
    params.require(:event).permit(:title, :severity, :description, :location, :date, :start_time, :end_time) 
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/edit.html.erb
<%= simple_form_for @event do |f| %>
<div class="box bordered-box blue-border">
  <div class="box-header blue-background">
    <div class="title">
      <i class="icon-plus"></i>
      Edit <% @event.title %>
    </div>
  </div>
  <div class="box-content box-double-padding">
    <form class="form" style="margin-bottom: 0;">
      <fieldset>
        <div class="col-sm-4">
          <div class="box">
        </div>
        <div class="col-sm-7 col-sm-offset-1">
          <div class="form-group">
           <%= f.input :title, :input_html => { :class => "form-control" } %>  
          </div>
          <div class="form-group">
           <%= f.input :severity, collection: Event.severity, :input_html => { :class => "form-control" } %>  
            </p>
          </div>
          <div class="form-group">
         <%= f.input :description, :input_html => { :class => "form-control" } %> 
          </div>
          <div class="form-group">
         <%= f.input :location, :input_html => { :class => "form-control" } %> 
          </div>
          <div class="form-group">
         <%= f.input :latitude, :input_html => { :class => "form-control" } %> 
          </div>
          <div class="form-group">
         <%= f.input :longitude, :input_html => { :class => "form-control" } %> 
          </div>
          <div class="form-group">
         <%= f.input :date, :input_html => { :class => "form-control" } %> 
          </div>
          <div class="form-group">
         <%= f.input :start_time, :input_html => { :class => "form-control" } %> 
          </div>
          <div class="form-group">
         <%= f.input :end_time, :input_html => { :class => "form-control" } %> 
          </div>
          <div class="form-group">
           <%= f.button :submit, :input_html => { :class => "btn btn-primary btn-lg" } %>  
           <% end %>
            </div>
          </div>
        </div>
        </div>
      </div>
    </form>
  </div>
</div>





 
 

app/views/events/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="box bordered-box red-border" style="margin-bottom:0;">
      <div class="box-header red-background">
        <div class="title">Look at all these things you should avoid</div>
      </div>
      <div class="box-content box-no-padding">
        <div class="responsive-table">

      <div class="col-sm-12 text-right">
          
              <%= search_form_for @search do |f| %>
       <div class="navbar-form navbar-right" >
        <%= f.text_field :title_or_location_cont, :class => "form-control input-sm"  %>
        <div class="actions"><%= f.submit "Search", :class => "icon-signout" %></div>
      <% end %>
        </div>
        </div>
      </div>
          <div class="scrollable-area">
            <table class="table table-hover table-striped" style="margin-bottom:0;">
              <thead>
                <tr>
                  <th><%= sort_link @search, :name, "Title" %></th>

                  <th><%= sort_link @search, :severity, "Severity" %></th>
      
                 <th><%= sort_link @search, :location, "Location" %></th>
                  
                  <th><%= sort_link @search, :date, "Date" %></th>
                </tr>
              </thead>

              <tbody>
              <% @events.each do |event| %>
              <tr>

              <td><%= link_to(event.title, event) %></td>

              <td><%= link_to(event.severity, event) %></td>

              <td><%= link_to(event.location, event) %></td>

              <td><%= link_to(event.date, event) %></td>

              <tr>
              <% end %> 

              </tbody>
          
            </table>            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<%= simple_form_for @event do |f| %>
<div class="box bordered-box blue-border">
  <div class="box-header blue-background">
    <div class="title">
      <i class="icon-plus"></i>
      Add a new event
    </div>
  </div>
  <div class="box-content box-double-padding">
    <form class="form" style="margin-bottom: 0;">
      <fieldset>
        <div class="col-sm-4">
          <div class="box">
        </div>
        <div class="col-sm-7 col-sm-offset-1">
          <div class="form-group">
           <%= f.input :title, :input_html => { :class => "form-control" } %>  
          </div>
          <div class="form-group">
           <%= f.input :severity, collection: Event.severity, :input_html => { :class => "form-control" } %>  
            </p>
          </div>
          <div class="form-group">
         <%= f.input :description, :input_html => { :class => "form-control" } %> 
          </div>
          <div class="form-group">
         <%= f.input :location, :input_html => { :class => "form-control" } %> 
          </div>
           <div class="form-group">
         <%= f.input :latitude, :input_html => { :class => "form-control", :id => "latitude" } %> 
          </div>
          <div class="form-group">
         <%= f.input :longitude, :input_html => { :class => "form-control", :id => "longitude" } %> 
          </div>
          <div class="form-group">
         <%= f.date_select :date, :order => [:month, :day, :year] %> 
          </div>
          <div class="form-group">
            <strong>Start Time:</strong>
          <%= f.time_select :start_time, {ampm: true} %> 
          </div>
          <div class="form-group">
          <strong>End Time:</strong>
         <%= f.time_select :end_time, {ampm: true}  %> 
          </div>
          <div class="form-group">
           <%= f.button :submit, :input_html => { :class => "btn btn-primary btn-lg" } %>  
           <% end %>
            </div>
          </div>
        </div>
        </div>
      </div>
    </form>
  </div>
</div>





 
 

app/views/events/show.html.erb
<h1> <%= @event.title %> </h1>

      <p>
        <strong>Severity:</strong>
        <%= @event.severity %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @event.description %>
      </p>


      <p>
        <strong>Location:</strong>
        <%= @event.location %>
      </p>

      <p>
        <strong>Date:</strong>
        <%= @event.date %>
      </p>

      <p>
        <strong>Start Time:</strong>
        <%= @event.start_time %>
      </p>

      <p>
        <strong>End Time:</strong>
        <%= @event.end_time %>
      </p>

      <%= link_to "Update Event", controller: "events", action: "edit", id: @event, :class => "button" %>
    



    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdedapp</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css" />
  <link href='http://api.tiles.mapbox.com/mapbox.js/v1.3.1/mapbox.css' rel='stylesheet' />
  <link href='http://api.tiles.mapbox.com/mapbox.js/v1.3.1/mapbox.ie.css' rel='stylesheet' >
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <nav class="navbar navbar-default">
 
    <!-- crowded logo -->
   <%= link_to 'Crowded', events_path, :class => "navbar-brand" %>
 
    <!-- main nav toggler (show/hide) -->
    <a class="toggle-nav btn pull-left" href="#">
      <i class="icon-reorder"></i>
    </a>
 
    <!-- dropdowns -->
    <ul class="nav">
 
      <!-- dark dropdown & user menu -->
      <li class="dropdown dark user-menu">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <% if user_signed_in? %>
          <%= current_user.email %>
          <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
          <% end %>
 
        </a>
        <ul class="dropdown-menu">
              <li>
                <%= link_to 'Edit profile', edit_user_registration_path, :class => "icon-user" %>
              </li>
              <li class="divider"></li>
              <li>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete, :class => "icon-signout" %>
              </li>
            </ul>
      </li>
    </ul>
 
    <!-- search form - hidden on phone -->
    
  </nav>
</header>


<div id="wrapper">
      <div id="main-nav-bg"></div>
      <nav id="main-nav">
        <div class="navigation">
          <div class="search">
            <form action="search_results.html" method="get">
              <div class="search-wrapper">
                <input value="" class="search-query form-control" placeholder="Search..." autocomplete="off" name="q" type="text">
                <button class="btn btn-link icon-search" name="button" type="submit"></button>
              </div>
            </form>
      </div>
   
      <!-- navigation shizzle -->
      <ul class="nav nav-stacked">
   
        <li class="active">
          <%= link_to events_path do  %>
            <i class="icon-home"></i>
            <span>Home</span>
            <% end %>
        </li>
        
        <li class="active">
          <%= link_to new_event_path do  %>
            <i class="icon-plus"></i>
            <span>Add Event</span>
            <% end %>
        </li>
      </ul>

      </div>
    </div>
  </nav>
  </div>
</div>

<section id="content">
  <% if notice %>
  <p class="alert alert-notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-error"><%= alert %></p>
<% end %>

<div id="map"></div>
<%= yield %>
</section>

<script src="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js"></script>
<script src='http://api.tiles.mapbox.com/mapbox.js/v1.3.1/mapbox.js'></script>
</body>
</html>

app/views/welcome/index.html.erb
Welcome to the party Richtor